import {
  javascript,
  typescript,
  html,
  css,
  reactjs,
  redux,
  tailwind,
  nodejs,
  mongodb,
  git,
  figma,
  docker,
  meta,
  starbucks,
  tesla,
  threejs,
  vr,
  unity,
  software_engineer,
  generative_ai,
  unity_colorful,
  stanford,
  api,
  blender,
  csharp,
  firebase,
  c,
  cpp,
  dart,
  flutter,
  python,
  unity3d,
  unreal_engine,
  unreal_engine_inverted,
  postman,
  threejs_inverted,
  me,
  github,
  instagram,
  outlook,
  stanfordxr,
  stanford_square,
  swinburne,
  freecodecamp,
  cybersecurity,
  aws,
  swift,
  minimalism,
  lifestyle,
  japan,
  hanhtrinh,
  languages,
  reading,
  cooking,
  travel,
  hagoromo,
  banh_mi_siro,
  facebook,
  logovideodemo,
} from "../assets";

export const navLinks = [
  {
    id: "about",
    title: "About",
  },
  {
    id: "work",
    title: "Blog",
  },
  {
    id: "projects",
    title: "Projects",
  },
  {
    id: "programs",
    title: "Education & Learning",
  },
  {
    id: "contact",
    title: "Contact",
  },
];

export const navMedia = [
  {
    id: "Instagram",
    image: instagram,
    link: "https://www.instagram.com/ssiiroo09.29/?igsh=emZkOG1neW5hcnht&utm_source=qr#",
  },
  {
    id: "GitHub",
    image: github,
    link: "https://github.com/Sirooo2k1",
  },
  {
    id: "Email",
    image: outlook,
    link: "mailto:REDACTED_EMAIL",
  },
];

export const blogCategories = [
  "My Journey",
  "Life in Japan",
  "Cooking",
  "Explore & Travel",
];

const services = [
  {
    title: "AR/VR Developer",
    icon: vr,
  },
  {
    title: "Unity Developer",
    icon: unity,
  },
  {
    title: "Software Engineer",
    icon: software_engineer,
  },
  {
    title: "Generative AI Engineer",
    icon: generative_ai,
  },
];

const technologies = [
  {
    name: "Python",
    icon: python,
  },
  {
    name: "Swift",
    icon: swift,
  },
  {
    name: "C#",
    icon: csharp,
  },
  {
    name: "C++",
    icon: cpp,
  },
  {
    name: "JavaScript",
    icon: javascript,
  },
  {
    name: "HTML 5",
    icon: html,
  },
  {
    name: "CSS 3",
    icon: css,
  },
  {
    name: "React",
    icon: reactjs,
  },
  {
    name: "Three JS",
    icon: threejs_inverted,
  },
  {
    name: "Unity",
    icon: unity3d,
  },
  {
    name: "Unreal Engine",
    icon: unreal_engine_inverted,
  },
  {
    name: "Blender",
    icon: blender,
  },
  {
    name: "Flutter",
    icon: flutter,
  },
];

const experiences = [
  {
    title: "My Journey Studying Abroad in Japan",
    company_name: "The Decision That Changed My Life",
    icon: hanhtrinh,
    iconBg: "#E6DEDD",
    date: "Category: My Journey",
    points: [
      "    It's been a while since I last sat down, opened my laptop, and wrote a few lines about my study abroad journey in Japan. Everything happened so quickly that sometimes I forget the feelings of those very first days—the emotions that were both bewildering and exciting, mixed with a little trembling. Today, I want to record this story, both to remember and to remind myself that some choices truly change the course of our entire lives.",
    ],
    // Multi-language support
    titleByLanguage: {
      en: "My Journey Studying Abroad in Japan",
      vi: "Hành Trình Du Học Nhật Bản",
      ja: "日本留学の旅路",
    },
    companyNameByLanguage: {
      en: "The Decision That Changed My Life",
      vi: "Quyết Định Thay Đổi Cuộc Đời Mình",
      ja: "人生を変えた決断",
    },
    dateByLanguage: {
      en: "Category: My Journey",
      vi: "Danh mục: Hành Trình Của Mình",
      ja: "カテゴリー: 私の旅路",
    },
    pointsByLanguage: {
      en: [
        "    It's been a while since I last sat down, opened my laptop, and wrote a few lines about my study abroad journey in Japan. Everything happened so quickly that sometimes I forget the feelings of those very first days—the emotions that were both bewildering and exciting, mixed with a little trembling. Today, I want to record this story, both to remember and to remind myself that some choices have changed my entire life.",
      ],
      vi: [
        "    Có lẽ đã lâu rồi mình mới chịu ngồi xuống, mở laptop và viết vài dòng về hành trình du học Nhật của chính mình. Mọi thứ diễn ra nhanh đến mức đôi khi mình quên mất cảm giác của những ngày đầu tiên – những cảm xúc vừa bỡ ngỡ, vừa háo hức, vừa xen lẫn một chút run rẩy. Hôm nay, mình muốn ghi lại câu chuyện này, vừa để nhớ, vừa để nhắc bản thân rằng: có những lựa chọn đã thay đổi cả cuộc đời mình.",
      ],
      ja: [
        "    もうずいぶん久しぶりに、ノートパソコンを開いて、自分の日本留学の旅について数行書きました。すべてがあまりにも早く起こったため、時には最初の数日間の感情を忘れてしまいます—困惑と興奮が混ざり合い、少し震えを伴う感情です。今日、この物語を記録したいと思います。記憶を保つため、そして、いくつかの選択が私の人生全体を本当に変えたことを自分に思い出させるためです。",
      ],
    },
  },
  {
    title: "The Moment That Changed My Life",
    company_name: "Why Did I Even Study Abroad?",
    icon: japan,
    iconBg: "#E6DEDD",
    date: "Category: Life in Japan",
    points: [
      "    On a rainy autumn evening in Japan, as the downpour blurred the world outside my small room, I lay on my bed staring out the window, letting my thoughts drift. Then suddenly, a question popped into my mind: Why did I study abroad? A question I wasn't asking anyone else—but asking myself. I realized I had been too busy to live, too hurried to feel. And from that night on, I began again—slowly, gently—from the smallest things. Studying abroad, for me, is also a journey of learning to listen to myself, learning to slow down, learning to uncover the feelings I buried under the rush of everyday life.",
    ],
    // Multi-language support
    titleByLanguage: {
      en: "The Moment That Changed My Life",
      vi: "Khoảnh Khắc Thay Đổi Cuộc Đời Mình",
      ja: "人生を変えた瞬間",
    },
    companyNameByLanguage: {
      en: "Why Did I Even Study Abroad?",
      vi: "Du Học Để Làm Gì?",
      ja: "なぜ留学したのか？",
    },
    dateByLanguage: {
      en: "Category: Life in Japan",
      vi: "Danh mục: Cuộc Sống Ở Nhật",
      ja: "カテゴリー: 日本での生活",
    },
    pointsByLanguage: {
      en: [
        "    On a rainy autumn evening in Japan, as the downpour continued, from my small room, I lay on my bed, looking out the window and thinking about various things. Then, a question suddenly appeared in my mind: \"Why did I study abroad?\". A question that I myself asked to question myself.",
      ],
      vi: [
        "    Vào một buổi tối chiều thu Nhật Bản, trời đổ mưa tầm tã, từ căn phòng nhỏ, mình nằm trên giường, nhìn ra ngoài cửa sổ và nghĩ ngợi linh tinh. Thế rồi, một câu hỏi bỗng xuất hiện trong đầu mình: \"Đi du học để làm gì?\". Một câu hỏi mà chính mình đặt ra để chất vấn bản thân.",
      ],
      ja: [
        "    日本の雨の秋の夜、激しい雨が降り続く中、小さな部屋から、ベッドに横たわり、窓の外を見つめながら、あれこれ考えていました。そして突然、頭に質問が浮かびました：「留学するのは何のため？」。自分自身に問いかける質問です。",
      ],
    },
  },
  {
    title: "When Cooking Became Part of My Life",
    company_name: "The simple joys of cooking",
    icon: cooking,
    iconBg: "#E6DEDD",
    date: "Category: Cooking",
    points: [],
    // Multi-language support
    titleByLanguage: {
      en: "When Cooking Became Part of My Life",
      vi: "Khi Nấu Ăn Trở Thành Một Phần Cuộc Sống Của Mình",
      ja: "料理が人生の一部になったとき",
    },
    companyNameByLanguage: {
      en: "The simple joys of cooking",
      vi: "Niềm Vui Đơn Giản Từ Việc Nấu Ăn",
      ja: "料理のシンプルな喜び",
    },
    dateByLanguage: {
      en: "Category: Cooking",
      vi: "Danh mục: Nấu Ăn",
      ja: "カテゴリー: 料理",
    },
    pointsByLanguage: {
      en: [],
      vi: [],
      ja: [],
    },
  },
  {
    title: "Exploring the World",
    company_name: "Unforgettable Journeys",
    icon: travel,
    iconBg: "#E6DEDD",
    date: "Category: Explore & Travel",
    points: [],
    // Multi-language support
    titleByLanguage: {
      en: "Exploring the World",
      vi: "Khám Phá Thế Giới",
      ja: "世界を探索する",
    },
    companyNameByLanguage: {
      en: "Unforgettable Journeys",
      vi: "Những Chuyến Đi Đáng Nhớ",
      ja: "忘れられない旅",
    },
    dateByLanguage: {
      en: "Category: Explore & Travel",
      vi: "Danh mục: Khám Phá & Du Lịch",
      ja: "カテゴリー: 探索と旅行",
    },
    pointsByLanguage: {
      en: [],
      vi: [],
      ja: [],
    },
  },
];

const testimonials = [
  {
    testimonial:
      "I thought it was impossible to make a website as beautiful as our product, but Rick proved me wrong.",
    name: "Sara Lee",
    designation: "CFO",
    company: "Acme Co",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    testimonial:
      "I've never met a web developer who truly cares about their clients' success like Rick does.",
    name: "Chris Brown",
    designation: "COO",
    company: "DEF Corp",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    testimonial:
      "After Rick optimized our website, our traffic increased by 50%. We can't thank them enough!",
    name: "Lisa Wang",
    designation: "CTO",
    company: "456 Enterprises",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
  },
];

const projects = [
  {
    name: "Personal Portfolio",
    description:
      "Welcome to my website! I'd like to give special thanks to JavaScript Mastery for the ThreeJS template, which I've customized to create my own unique style. I also adapted Eli Shmerler's 'magical particles' effect to seamlessly integrate with the website, while exploring vertex and fragment shaders along the way.",
    // Multi-language support
    nameByLanguage: {
      en: "Personal Portfolio",
      vi: "Portfolio Cá Nhân",
      ja: "個人ポートフォリオ",
    },
    descriptionByLanguage: {
      en: "Welcome to my website! I want to give special thanks to JavaScript Mastery for the ThreeJS template, which I customized to create my own unique style. I also adapt Eli Shmerler's 'magical particles' effect to seamlessly integrate with the website, while exploring vertex and fragment shaders in the process.",
      vi: "Chào mừng đến với website của mình! Mình muốn cảm ơn đặc biệt JavaScript Mastery vì template ThreeJS, mà mình đã tùy chỉnh để tạo ra phong cách độc đáo của riêng mình. Mình cũng thích ứng hiệu ứng 'magical particles' của Eli Shmerler để tích hợp mượt mà với website, đồng thời khám phá vertex và fragment shaders trong quá trình đó.",
      ja: "私のウェブサイトへようこそ！ThreeJSテンプレートを提供してくれたJavaScript Masteryに特別な感謝を申し上げたいです。私は独自のスタイルを作成するためにカスタマイズしました。また、Eli Shmerlerの「magical particles」エフェクトを適応させて、ウェブサイトとシームレスに統合し、その過程で頂点シェーダーとフラグメントシェーダーを探索しています。",
    },
    tags: [
      {
        name: "ThreeJS",
        color: "green-text-gradient",
      },
      {
        name: "React",
        color: "green-text-gradient",
      },
      {
        name: "HTML",
        color: "blue-text-gradient",
      },
      {
        name: "Tailwind CSS",
        color: "pink-text-gradient",
      },
      {
        name: "Javascript",
        color: "blue-text-gradient",
      },
      {
        name: "Shaders",
        color: "pink-text-gradient",
      },
      {
        name: "Vercel",
        color: "green-text-gradient",
      },
    ],
    image: me,
    source_code_link: "https://github.com/Sirooo2k1",
    live_link: "https://portfoliosiro.vercel.app/",
  },
  {
    name: "My First Website",
    description:
      "This is the first web project I developed, transforming an idea into a vibrant shopping experience. The website features a modern design with a rich and diverse menu, making it easy for users to explore and select their favorite dishes. What I'm most proud of is the AI chatbot — an intelligent virtual assistant that's always ready to chat, suggest dishes, and guide customers through the ordering process, delivering an engaging, convenient, and warm experience.",
    // Multi-language support
    nameByLanguage: {
      en: "My First Website",
      vi: "Website Đầu Tiên Của Mình",
      ja: "私の最初のウェブサイト",
    },
    descriptionByLanguage: {
      en: "This is the first web project I developed, where I transformed an idea into a vibrant shopping experience for customers. The website is designed with a modern style featuring a rich and diverse menu, helping users easily explore and select their favorite dishes. The highlight that makes me most proud is the AI chatbot — an intelligent virtual assistant always ready to chat, suggest dishes, and guide customers step by step through the ordering process, bringing an interesting, convenient, and close shopping experience like a true companion.",
      vi: "Đây là dự án web đầu tiên mình phát triển, nơi mình biến ý tưởng thành trải nghiệm mua sắm sống động cho khách hàng. Website được thiết kế hiện đại với menu phong phú, đa dạng, giúp người dùng dễ dàng khám phá và lựa chọn món ăn yêu thích. Điểm nhấn khiến mình tự hào nhất là AI chatbot — người trợ lý ảo thông minh luôn sẵn sàng trò chuyện, gợi ý món ăn và hướng dẫn khách hàng từng bước trong quá trình đặt hàng, mang đến trải nghiệm mua sắm thú vị, tiện lợi và gần gũi như một người bạn đồng hành thực sự.",
      ja: "これは私が開発した最初のウェブプロジェクトで、アイデアを顧客のための活気あるショッピング体験に変えた場所です。ウェブサイトは豊かで多様なメニューを備えたモダンなデザインで、ユーザーが簡単に探索し、お気に入りの料理を選択できるようになっています。最も誇りに思っている点は、AIチャットボットです—常にチャット、料理の提案、注文プロセスの各ステップで顧客を案内する準備ができている、インテリジェントな仮想アシスタントで、楽しく、便利で、親しみやすいショッピング体験を提供し、まるで本当の仲間のように感じさせます。",
    },
    tags: [
      {
        name: "HTML",
        color: "blue-text-gradient",
      },
      {
        name: "Tailwind CSS",
        color: "pink-text-gradient",
      },
      {
        name: "JavaScript",
        color: "blue-text-gradient",
      },
      {
        name: "NodeJS",
        color: "green-text-gradient",
      },
      {
        name: "AI Chatbot",
        color: "orange-text-gradient",
      },
      {
        name: "Vercel",
        color: "green-text-gradient",
      },
    ],
    image: banh_mi_siro,
    source_code_link: "https://github.com/Sirooo2k1",
    live_link: "https://banhmisiroagent.vercel.app/",
  },
  {
    name: "Analytics Dashboard & AI Agent",
    description:
      "This intelligent backend system processes and analyzes customer data in real-time. It collects all customer conversations and uses an AI agent to automatically classify them as spam or potential leads. Valid inquiries are seamlessly routed to the Order management section with complete details—name, phone number, email, and order specifications. The system integrates with Make.com to automatically generate and send confirmation emails, streamlining workflows and ensuring a professional customer experience.",
    tags: [
      {
        name: "NodeJS",
        color: "green-text-gradient",
      },
      {
        name: "Make.com",
        color: "green-text-gradient",
      },
      {
        name: "Data Analytics",
        color: "blue-text-gradient",
      },
      {
        name: "AI Agent",
        color: "orange-text-gradient",
      },
      {
        name: "Supabase",
        color: "pink-text-gradient",
      },
      {
        name: "Vercel",
        color: "green-text-gradient",
      },
    ],
    image: logovideodemo,
    source_code_link: "https://www.facebook.com/share/v/18u4GpopRY/",
    source_code_icon: facebook,
    youtube_demo_link: null, // Add Facebook video link here
    live_link: null,
    // Multi-language support
    nameByLanguage: {
      en: "Analytics Dashboard & AI Agent",
      vi: "Bảng Điều Khiển Phân Tích & AI Agent",
      ja: "分析ダッシュボード & AIエージェント",
    },
    descriptionByLanguage: {
      en: "This is the backend part I built as an intelligent data processing system, collecting all customer conversations. Then, analyzing them using an AI agent, the AI will automatically classify conversations as spam or potential customers, then transfer valid requests to the Order section with complete information such as name, phone number, email, and order details. In this backend part, I also connected with Make.com to automatically create and send confirmation emails, helping to optimize the ordering process and bringing a fresh, fast, and reliable experience to customers.",
      vi: "Đây là phần backend được mình xây dựng như một hệ thống xử lý dữ liệu thông minh, thu thập toàn bộ cuộc trò chuyện của khách hàng. Sau đó, phân tích chúng bằng AI agent, AI sẽ tự động phân loại hội thoại thành spam hoặc khách hàng tiềm năng, rồi chuyển các yêu cầu hợp lệ vào mục Order với đầy đủ thông tin như tên, số điện thoại, email và chi tiết đơn hàng. Trong phần backend này mình cũng kết nối với Make.com để tự động tạo và gửi email xác nhận, giúp tối ưu hóa quy trình đặt hàng và mang đến trải nghiệm mới mẻ, nhanh chóng và đáng tin cậy cho khách hàng.",
      ja: "これは私が構築したバックエンド部分で、インテリジェントなデータ処理システムとして機能し、すべての顧客会話を収集します。その後、AIエージェントを使用して分析し、AIが会話をスパムまたは潜在的な顧客に自動的に分類し、有効なリクエストを名前、電話番号、メールアドレス、注文詳細などの完全な情報とともにOrderセクションに転送します。このバックエンド部分では、Make.comと接続して確認メールを自動的に作成・送信し、注文プロセスを最適化し、顧客に新鮮で、迅速で、信頼できる体験を提供します。",
    },
  },
];

const programs = [
  {
    company: "Hagoromo University",
    title: "Information Systems Student",
    icon: hagoromo,
    date: "2024 - Present",
    description:
      "Pursuing a degree in Information Systems, specializing in software development, data management, and Unity game development.\nCompleted key courses in data structures and algorithms, data analysis, database management, and web development. Actively exploring and executing real-world projects, applying knowledge to practical applications while developing teamwork skills.\n\nKey Highlights:\n• Designed and implemented a web application integrating an AI Agent with a database for coursework.\n• Built a data visualization dashboard to analyze real-world datasets.\n• Applied information security principles and management practices in projects.\n• Collaborated in team projects using Agile methodology and Git version control.",
    // Multi-language support
    companyByLanguage: {
      en: "Hagoromo University",
      vi: "Đại Học Hagoromo",
      ja: "羽衣大学",
    },
    titleByLanguage: {
      en: "Information Systems Student",
      vi: "Sinh Viên Hệ Thống Thông Tin",
      ja: "情報システム学生",
    },
    descriptionByLanguage: {
      en: "Currently studying the Information Systems program with a focus on software development, data management, and game development using Unity. I have completed quite well courses such as data structures, algorithms, data analysis, database administration, and web development. Applying the knowledge I've learned to real-world projects, including designing and implementing web applications integrating AI Agent with databases and building data visualization dashboards, then analyzing them. Gained some additional experience in user information security and system management. Proficiently using Git for version control. Maintaining excellent academic performance while actively researching and exploring creative solutions.",
      vi: "Hiện tại mình đang theo học chương trình Hệ thống Thông tin với chuyên sâu về phát triển phần mềm, quản lý dữ liệu và phát triển game bằng Unity. Mình đã hoàn thành khá tốt các môn học như cấu trúc dữ liệu, giải thuật, phân tích dữ liệu, quản trị cơ sở dữ liệu và phát triển web. Áp dụng kiến thức đã học được vào các dự án thực tế, bao gồm thiết kế và triển khai ứng dụng web tích hợp AI Agent với cơ sở dữ liệu và xây dựng dashboard trực quan hóa dữ liệu, sau đó phân tích chúng. Tích lũy thêm được một số kinh nghiệm về bảo mật thông tin người dùng và quản lí hệ thống. Sử dụng thành thạo Git để quản lý phiên bản. Duy trì thành tích học tập xuất sắc đồng thời tích cực nghiên cứu và khám phá các giải pháp sáng tạo.",
      ja: "現在、情報システムのプログラムを学習中で、ソフトウェア開発、データ管理、Unityを使ったゲーム開発に特化しています。データ構造、アルゴリズム、データ分析、データベース管理、Web開発などの科目をかなり良好に完了しました。学んだ知識を実践的なプロジェクトに適用し、AIエージェントをデータベースと統合したWebアプリケーションの設計と実装、データ可視化ダッシュボードの構築とその後の分析などを行いました。ユーザー情報のセキュリティとシステム管理についてもいくつかの経験を積みました。Gitを習熟してバージョン管理を行っています。優秀な学業成績を維持しながら、積極的に研究し、創造的なソリューションを探求しています。",
    },
  },
  {
    company: "Swinburne University Lecturer",
    title: "Dung Lai Lap Trinh Course",
    icon: swinburne,
    date: "September 2023 - March 2025",
    description:
      "Successfully completed the entire programming learning pathway with outstanding performance, significantly strengthening programming skills and problem-solving abilities.\n\nCompleted courses include:\n• Logical & Mathematical Thinking\n• Python Programming (Beginner to Advanced)\n• Fundamentals of Web Development\n• Python for Excel Automation\n• Game Development\n• Foundations of Data Science\n• Introduction to AI Programming\n• Python & ChatGPT\n• AI Agent Development",
    // Multi-language support
    companyByLanguage: {
      en: "Swinburne University Lecturer",
      vi: "Giảng Viên Đại Học Swinburne",
      ja: "スウィンバーン大学講師",
    },
    titleByLanguage: {
      en: "Dung Lai Lap Trinh Course",
      vi: "Khóa Học Dung Lai Lập Trình",
      ja: "Dung Lai Lập Trìnhコース",
    },
    descriptionByLanguage: {
      en: "Completed excellently the entire programming learning pathway. Enhanced programming skills and problem-solving abilities.\n\nAll courses:\n• Logic Math\n• Python from basic to advanced\n• Basic Web Programming\n• Python Excel Automation\n• Game Programming\n• Basic Data Science\n• Basic AI Programming\n• Python ChatGPT\n• AI Agent Programming",
      vi: "Hoàn thành xuất sắc toàn bộ lộ trình học lập trình. Nâng cao kỹ năng lập trình và giải quyết vấn đề.\n\nTất cả khoá học:\n• Toán Logic\n• Python cơ bản đến nâng cao\n• Lập trình Web cơ bản\n• Python Excel Tự động hóa\n• Lập trình Game\n• Data Science cơ bản\n• Lập trình AI cơ bản\n• Python ChatGPT\n• Lập trình AI Agent",
      ja: "プログラミング学習パス全体を優秀な成績で完了しました。プログラミングスキルと問題解決能力を向上させました。\n\nすべてのコース：\n• 数学ロジック\n• Python基礎から上級まで\n• Webプログラミング基礎\n• Python Excel自動化\n• ゲームプログラミング\n• Data Science基礎\n• AIプログラミング基礎\n• Python ChatGPT\n• AIエージェントプログラミング",
    },
  },
  {
    company: "Hagoromo University",
    title: "Game Programming I & II",
    icon: unity,
    date: "2025",
    description:
      "Game Programming I\n      • This course marked my first steps into the world of game development. From simple movements to my first interactions in Unity, each lesson built another solid brick in the foundation of my first game project.\n      • Grade: 99/100\n\nGame Programming II\n      • If Game Programming I was the beginning, then Game Programming II was where I learned how to turn ideas into complete products. I built a Match-3 Puzzle Game from scratch: falling effects, match handling, scoring system, data persistence, UI, and game flow. This was the first time I truly felt the satisfaction of completing a real game. An incredible feeling that's difficult to put into words.\n      • Grade: 100/100",
    // Multi-language support
    companyByLanguage: {
      en: "Hagoromo University",
      vi: "Đại Học Hagoromo",
      ja: "羽衣大学",
    },
    titleByLanguage: {
      en: "Game Programming I & II",
      vi: "Lập Trình Game I & II",
      ja: "ゲームプログラミング I & II",
    },
    descriptionByLanguage: {
      en: "Game Programming I\n• This is the course that marked my first steps into the world of game development. From simple movements to my first interactions in Unity, each class session helped me build another solid \"brick\" for my first game project.\n• Score: 99/100\n\nGame Programming II\n• If Game Programming I was the starting point, then Game Programming II is where I learned how to turn ideas into a complete product. I built the Match-3 Puzzle Game from zero: falling effects, match handling, scoring system, data saving, UI, and the entire gameplay lifecycle. This was also the first time I truly felt the feeling of completing a game. A wonderful feeling that's hard to put into words.\n• Score: 100/100",
      vi: "Lập trình Game I\n• Đây là môn học đánh dấu những bước chân đầu tiên của mình vào thế giới phát triển game. Từ những chuyển động đơn giản cho đến những tương tác đầu tiên trong Unity, mỗi buổi học đều giúp mình xây thêm một \"viên gạch\" vững chắc cho dự án game đầu tay.\n• Điểm số: 99/100\n\nLập trình Game II\n• Nếu Lập trình Game I là điểm khởi đầu, thì Lập trình Game II là nơi mình học cách biến ý tưởng thành một sản phẩm hoàn chỉnh. Mình đã tự xây dựng trò chơi Match-3 Puzzle Game từ con số 0: hiệu ứng rơi, xử lý match, hệ thống điểm, lưu dữ liệu, UI và toàn bộ vòng đời gameplay. Đây cũng là lần đầu tiên mình thực sự cảm nhận được cảm giác hoàn thành một trò chơi. Một cảm giác tuyệt vời khó diễn tả bằng lời.\n• Điểm số: 100/100",
      ja: "ゲームプログラミング I\n• これは私のゲーム開発の世界への最初の一歩を記した科目です。シンプルな動きからUnityでの最初のインタラクションまで、各授業が私の最初のゲームプロジェクトのために「レンガ」を一つずつ堅固に積み上げるのに役立ちました。\n• 点数: 99/100\n\nゲームプログラミング II\n• ゲームプログラミング Iがスタート地点なら、ゲームプログラミング IIは私がアイデアを完全な製品に変える方法を学んだ場所です。ゼロからMatch-3パズルゲームを自分で構築しました：落下エフェクト、マッチ処理、スコアリングシステム、データ保存、UI、そしてゲームプレイの全ライフサイクル。これが初めて、一つのゲームを完成させる感覚を本当に感じた瞬間でもありました。言葉では表現できない素晴らしい感覚です。\n• 点数: 100/100",
    },
  },
  {
    company: "freeCodeCamp",
    title: "Full Stack Web Development",
    icon: freecodecamp,
    date: "September 2025 - Present",
    description:
      "This comprehensive course transformed my programming mindset and product approach. I learned how to turn ideas into real-world products through a challenging journey filled with valuable discoveries.\n\nKey Skills Developed:\n• Built numerous projects including web apps, APIs, and interactive interfaces\n• Developed systems thinking and problem-solving abilities\n• Gained deep understanding of both Frontend and Backend technologies\n\n→ Biggest Achievement: From zero programming experience to creating fully functional products with my own hands.",
    // Multi-language support
    companyByLanguage: {
      en: "freeCodeCamp",
      vi: "freeCodeCamp",
      ja: "freeCodeCamp",
    },
    titleByLanguage: {
      en: "Full Stack Web Development",
      vi: "Phát Triển Web Full Stack",
      ja: "フルスタックWeb開発",
    },
    descriptionByLanguage: {
      en: "This comprehensive course changed my programming mindset and product approach. I learned how to turn ideas into real-world products through a challenging journey with many valuable discoveries.\n\nKey Skills Developed:\n• Built many projects including web applications, APIs, and interactive interfaces\n• Developed systems thinking and problem-solving abilities\n• Deep understanding of both Frontend and Backend technologies\n\n→ Biggest Achievement: From no programming experience to creating complete products with full functionality with my own hands.",
      vi: "Khóa học toàn diện này đã thay đổi tư duy lập trình và cách tiếp cận sản phẩm của mình. Mình đã học cách biến ý tưởng thành sản phẩm thực tế qua một hành trình đầy thử thách với nhiều khám phá quý giá.\n\nKỹ Năng Chính Đã Phát Triển:\n• Xây dựng nhiều dự án bao gồm ứng dụng web, API và giao diện tương tác\n• Phát triển tư duy hệ thống và khả năng giải quyết vấn đề\n• Hiểu sâu về cả công nghệ Frontend và Backend\n\n→ Thành Tựu Lớn Nhất: Từ không có kinh nghiệm lập trình đến tạo ra các sản phẩm hoàn chỉnh, có đầy đủ chức năng bằng chính đôi tay của mình.",
      ja: "この包括的なコースは、私のプログラミングマインドセットと製品へのアプローチを変えました。貴重な発見に満ちた挑戦的な旅を通じて、アイデアを実世界の製品に変える方法を学びました。\n\n主に開発されたスキル：\n• Webアプリ、API、インタラクティブインターフェースを含む多数のプロジェクトを構築\n• システム思考と問題解決能力を開発\n• フロントエンドとバックエンドの両方のテクノロジーを深く理解\n\n→ 最大の成果：プログラミング経験ゼロから、自分の手で完全で、すべての機能を備えた製品を作成するまで。",
    },
  },
  {
    company: "Cybersecurity Journey",
    title: "Cybersecurity",
    icon: cybersecurity,
    date: "2026 - Planned",
    description:
      "2026 will mark the year I embark on my journey into cybersecurity. Not to become a hacker or expert, but to understand how to protect the products I build. I want to know what makes a system robust, what makes it vulnerable, and what creates a truly trustworthy application.\n\nI plan to start with the most fundamental foundations:\n• How networks and security protocols work behind the scenes\n• The mindset of an ethical hacker when identifying vulnerabilities\n• Common security pitfalls in web development and how to avoid them\n• Encryption principles that make data truly secure\n• And finally, how to respond when incidents actually occur",
    // Multi-language support
    companyByLanguage: {
      en: "Cybersecurity Journey",
      vi: "Hành Trình An Ninh Mạng",
      ja: "サイバーセキュリティの旅",
    },
    titleByLanguage: {
      en: "Cybersecurity",
      vi: "An Ninh Mạng",
      ja: "サイバーセキュリティ",
    },
    descriptionByLanguage: {
      en: "2026 will be the year I want to step into the journey of learning about Cybersecurity. Not to become a hacker or expert, but to understand how to protect the products I build. I want to know what makes a system strong, what makes it vulnerable, and what creates a truly trustworthy application.\n\nI plan to start from the most important foundations:\n• How networks and security protocols work behind the scenes\n• The mindset of an ethical hacker when searching for weaknesses\n• Common security mistakes in web and how to avoid them\n• Encryption principles that make data become \"impregnable\"\n• And finally, how to respond when incidents actually occur",
      vi: "2026 sẽ là năm mà mình muốn bước vào hành trình học về Cybersecurity. Không phải để trở thành hacker hay chuyên gia, mà là để hiểu cách bảo vệ những sản phẩm mình xây dựng. Mình muốn biết điều gì khiến một hệ thống trở nên mạnh mẽ, điều gì khiến nó dễ bị tổn thương, và điều gì tạo ra một ứng dụng thật sự đáng tin cậy.\n\nMình dự định sẽ bắt đầu từ những nền tảng quan trọng nhất:\n• Cách mạng và giao thức bảo mật hoạt động phía sau hậu trường\n• Tư duy của một ethical hacker khi tìm kiếm điểm yếu\n• Những sai lầm bảo mật thường gặp trong web và cách tránh\n• Các nguyên tắc mã hóa giúp dữ liệu trở nên \"bất khả xâm phạm\"\n• Và cuối cùng là cách phản ứng khi sự cố thực sự xảy ra",
      ja: "2026年は、私がCybersecurityを学ぶ旅に足を踏み入れたい年です。ハッカーや専門家になるためではなく、自分が構築する製品を保護する方法を理解するためです。システムを強力にするもの、システムを脆弱にするもの、そして真に信頼できるアプリケーションを作成するものを知りたいです。\n\n最も重要な基盤から始めることを計画しています：\n• ネットワークとセキュリティプロトコルが舞台裏でどのように機能するか\n• 弱点を探す際のethical hackerのマインドセット\n• Webでよく見られるセキュリティの誤りとそれらを回避する方法\n• データを「侵入不可能」にする暗号化の原則\n• そして最後に、インシデントが実際に発生したときにどのように対応するか",
    },
  },
  {
    company: "AWS Learning Path",
    title: "Cloud Computing",
    icon: aws,
    date: "2026 - Planned",
    description:
      "Throughout my programming journey, I've always been curious: How can a small application on my computer serve thousands, even millions of people out there?\nThe answer I discovered is cloud computing, the platform that powers modern applications.\n\nMy AWS journey will begin with the most fundamental foundations:\n• Understanding the AWS ecosystem and how services interconnect and support each other to create a flexible and powerful platform\n• Building scalable architectures and sustainable systems that adapt to application scale and expand when needed\n• Optimizing performance and cost by balancing speed, stability, and budget\n• Applying Well-Architected principles to deploy, monitor, and operate professionally according to industry standards",
    // Multi-language support
    companyByLanguage: {
      en: "AWS Learning Path",
      vi: "Lộ Trình Học AWS",
      ja: "AWS学習パス",
    },
    titleByLanguage: {
      en: "Cloud Computing",
      vi: "Điện Toán Đám Mây",
      ja: "クラウドコンピューティング",
    },
    descriptionByLanguage: {
      en: "Throughout my programming journey, I've always been curious: How can a small application on my computer serve thousands, even millions of people out there?\nThe answer I discovered is cloud computing, the platform that provides power for modern applications.\n\nMy AWS journey will start from the most fundamental foundations:\n• Understanding the AWS ecosystem and how services connect and support each other to create a flexible and powerful platform\n• Building scalable architectures and sustainable systems that adapt to application scale and expand when needed\n• Optimizing performance and cost by balancing speed, stability, and budget\n• Applying Well-Architected principles to deploy, monitor, and operate professionally according to industry standards",
      vi: "Trong suốt hành trình lập trình của mình, mình luôn tò mò: Làm thế nào một ứng dụng nhỏ trên máy tính của mình có thể phục vụ hàng nghìn, thậm chí hàng triệu người ngoài kia?\nCâu trả lời mình khám phá được là điện toán đám mây, nền tảng cung cấp sức mạnh cho các ứng dụng hiện đại.\n\nHành trình AWS của mình sẽ bắt đầu với những nền tảng cơ bản nhất:\n• Hiểu hệ sinh thái AWS và cách các dịch vụ kết nối và hỗ trợ lẫn nhau để tạo ra một nền tảng linh hoạt và mạnh mẽ\n• Xây dựng kiến trúc có thể mở rộng và hệ thống bền vững thích ứng với quy mô ứng dụng và mở rộng khi cần\n• Tối ưu hóa hiệu suất và chi phí bằng cách cân bằng tốc độ, ổn định và ngân sách\n• Áp dụng các nguyên tắc Well-Architected để triển khai, giám sát và vận hành chuyên nghiệp theo tiêu chuẩn ngành",
      ja: "プログラミングの旅を通じて、私は常に好奇心を持っていました：コンピュータ上の小さなアプリケーションが、どのようにして何千人、何百万人もの人々にサービスを提供できるのか？\n私が発見した答えは、クラウドコンピューティング、現代のアプリケーションに力を与えるプラットフォームです。\n\n私のAWSの旅は、最も基本的な基盤から始まります：\n• AWSエコシステムと、サービスが相互に接続し、サポートして柔軟で強力なプラットフォームを作成する方法を理解する\n• アプリケーションの規模に適応し、必要に応じて拡張するスケーラブルなアーキテクチャと持続可能なシステムを構築する\n• 速度、安定性、予算のバランスを取ることにより、パフォーマンスとコストを最適化する\n• Well-Architectedの原則を適用して、業界標準に従って専門的に展開、監視、運用する",
    },
  },
];

// Blog Posts Data
export const blogPosts = [
  {
    slug: "the-decision-that-changed-my-life",
    title: "My Journey Studying Abroad in Japan",
    subtitle: "The Decision That Changed My Life",
    category: "My Journey",
    date: "November 2025",
    content: [
      "It's been a while since I last sat down, opened my laptop, and wrote a few lines about my study abroad journey in Japan. Everything happened so quickly that sometimes I forget the feelings of those very first days—the emotions that were both bewildering and exciting, mixed with a little trembling. Today, I want to record this story, both to remember and to remind myself that some choices truly change the course of our entire lives.",
      "The decision to study abroad — born from a very simple desire. Back then, I didn't have any grand dreams. I simply wanted to try living somewhere far away—away from my parents' embrace, away from everything that had become too familiar, just to challenge myself. Japan, at that time, was still a distant place to me, a country I only knew through my siblings' stories, through photos, and through tales of diligent, hardworking, resilient people.",
      "Then came the preparation: documents, paperwork, financial proof, interviews… Everything went surprisingly smoothly, perhaps even faster than I expected. Except for one thing… I only had two months to learn Japanese before leaving. Just two short months for such a long journey.",
      "The day I left — a whirlwind of emotions. I still remember that day clearly, the day I wheeled my suitcase into the airport. Everything blended together: excitement, worry, anticipation, and even a hint of fear, even though I knew I would be living with my siblings once I arrived. The moment I saw my parents waving goodbye, I suddenly felt a little more \"grown up,\" yet also strangely small. The long flight passed by, oddly enough, very quickly.",
      "The first days in Japan — beautiful, unfamiliar, and filled with homesickness. Japan, through my eyes the very first time, was clean air, hurried streams of people walking, and trains so punctual it was almost unbelievable. But there were also things that reminded me I hadn't quite caught up yet: Getting lost a few times, Japanese that sounded like something I had never learned, and nights filled with homesickness and longing for my parents.",
      "Yet with each passing day, I grew a little more used to everything. I began babbling my first Japanese sentences. I learned how to take the train without needing directions. I started making my first friends. And before I knew it, Japan had quietly become a part of my life.",
      "Looking back. The journey wasn't always smooth. There were days when I felt so sad I wanted to cry, moments of exhaustion, and loneliness so deep I almost wanted to give up. But if I could choose again, I would still choose Japan. I would still choose to leave. I would still choose this journey.",
      "Thank you to the version of myself back then—the one who dared to take such a big step.",
    ],
    // Multi-language support
    titleByLanguage: {
      en: "My Journey Studying Abroad in Japan",
      vi: "Hành Trình Du Học Nhật Bản",
      ja: "日本留学の旅路",
    },
    subtitleByLanguage: {
      en: "The Decision That Changed My Life",
      vi: "Quyết Định Thay Đổi Cuộc Đời Mình",
      ja: "人生を変えた決断",
    },
    categoryByLanguage: {
      en: "My Journey",
      vi: "Hành Trình Của Mình",
      ja: "私の旅路",
    },
    contentByLanguage: {
      en: [
        "My study abroad journey in Japan",
        "",
        "It's been a while since I last sat down, opened my laptop, and wrote a few lines about my study abroad journey in Japan. Everything happened so quickly that sometimes I forget the feelings of those very first days—the emotions that were both bewildering and exciting, mixed with a little trembling. Today, I want to record this story, both to remember and to remind myself that some choices have changed my entire life.",
        "",
        "The decision to study abroad — starting from a very simple desire",
        "",
        "Back then, I didn't have any grand dreams. I simply wanted to try living somewhere far away from my parents' embrace, away from everything that had become too familiar, just to challenge myself.",
        "",
        "Japan, at that time, was still very unfamiliar to me, a country I only knew through my siblings' stories, through photos, and through tales of diligent, hardworking, resilient people.",
        "",
        "Then I began the preparation process: documents, paperwork, financial proof, interviews… Everything went very smoothly, perhaps even faster than I thought.",
        "",
        "Except for one thing… I only had two months to learn Japanese before leaving. Two short months for such a long journey.",
        "",
        "The day I left — so many emotions it's hard to describe",
        "",
        "The day I carried my suitcase to the airport, I still remember that feeling very clearly. Everything blended together: nervousness, worry, anticipation, and even a hint of fear, even though I knew I would be living with my siblings once I arrived.",
        "",
        "The moment I saw my parents waving goodbye, I naturally felt a little more \"grown up,\" but also felt strangely small.",
        "",
        "The flight was long, but strangely, it passed by really very quickly.",
        "",
        "My first few days in Japan — beautiful, unfamiliar, and full of homesickness",
        "",
        "The Japan I first saw was very clean air, streams of people walking hurriedly, trains so punctual it was… hard to believe.",
        "",
        "But there were also things that made me feel I hadn't quite caught up yet:",
        "",
        "* Getting lost a few times",
        "",
        "* Japanese that sounded like I'd never learned it",
        "",
        "* And every night missing home and missing my parents",
        "",
        "Still, as each day passed, I got used to everything a little more.",
        "",
        "I began to stammer out my first Japanese sentences. I began to know how to ride the train without needing directions. I began to have my first friends.",
        "",
        "And suddenly, I don't know when—Japan had quietly become part of my life.",
        "",
        "Looking back",
        "",
        "The journey wasn't always smooth. There were days when I felt so sad I wanted to cry, moments when I was exhausted, lonely to the point of wanting to give up.",
        "",
        "But if I could choose again, I would still choose Japan, I would still choose to leave, I would still choose this journey.",
      ],
      vi: [
        "Hành trình du học Nhật",
        "",
        "Có lẽ đã lâu rồi mình mới chịu ngồi xuống, mở laptop và viết vài dòng về hành trình du học Nhật của chính mình. Mọi thứ diễn ra nhanh đến mức đôi khi mình quên mất cảm giác của những ngày đầu tiên – những cảm xúc vừa bỡ ngỡ, vừa háo hức, vừa xen lẫn một chút run rẩy. Hôm nay, mình muốn ghi lại câu chuyện này, vừa để nhớ, vừa để nhắc bản thân rằng: có những lựa chọn đã thay đổi cả cuộc đời mình.",
        "",
        "Quyết định đi du học – bắt đầu từ một mong muốn rất giản đơn",
        "",
        "Ngày ấy, mình không có ước mơ gì quá lớn lao cả. Chỉ đơn giản là muốn thử sống ở một nơi thật xa rời xa vòng tay của bố mẹ, rời xa những thứ vốn đã quá quen thuộc để thử thách bản thân.",
        "",
        "Nhật Bản lúc đó với mình vẫn còn rất xa lạ, một đất nước mà mình chỉ được nghe qua lời kể của anh chị, những tấm ảnh và câu chuyện về những con người cần mẫn, chăm chỉ, chịu thương chịu khó.",
        "",
        "Rồi mình bắt đầu bước vào quá trình chuẩn bị: hồ sơ, giấy tờ, chứng minh tài chính, phỏng vấn… Tất cả đều diễn ra rất suôn sẻ, có lẽ còn nhanh hơn cả suy nghĩ của mình.",
        "",
        "Chỉ có điều… mình chỉ có vỏn vẹn hai tháng để học tiếng Nhật trước khi lên đường. Hai tháng ít ỏi cho một chuyến đi dài.",
        "",
        "Ngày lên đường – nhiều cảm xúc đến khó tả",
        "",
        "Ngày xách vali ra sân bay, mình vẫn nhớ rất rõ cảm giác đó. Mọi thứ hòa quyện vào nhau: hồi hộp, lo lắng, mong chờ, và cả một chút sợ hãi, mặc dù mình biết sang đó mình sẽ được ở cùng anh chị.",
        "",
        "Khoảnh khắc nhìn bố mẹ vẫy tay chào, tự nhiên thấy mình \"trưởng thành\" hơn một chút, nhưng cũng thấy mình nhỏ bé đến lạ thường.",
        "",
        "Chuyến bay dài, nhưng lạ thay, nó trôi qua thật sự rất nhanh.",
        "",
        "Những ngày đầu ở Nhật – đẹp, lạ và đầy thương nhớ",
        "",
        "Nhật Bản lần đầu trong mắt mình là bầu không khí rất sạch, dòng người đi bộ hối hả, tàu đúng giờ đến mức… khó tin.",
        "",
        "Nhưng cũng có những thứ khiến mình cảm thấy chưa thật sự bắt nhịp được:",
        "",
        "* Lạc đường vài lần",
        "",
        "* Tiếng Nhật nghe như chưa từng được học",
        "",
        "* Và tối nào cũng nhớ nhà nhớ bố mẹ",
        "",
        "Thế nhưng, mỗi ngày trôi qua mình lại quen hơn một chút.",
        "",
        "Bắt đầu bập bẹ nói những câu tiếng Nhật đầu tiên. Bắt đầu tự biết đi tàu mà không cần chỉ dẫn. Bắt đầu có những người bạn đầu tiên.",
        "",
        "Và bỗng dưng không biết từ khi nào – Nhật Bản đã lặng lẽ trở thành một phần cuộc sống của mình.",
        "",
        "Khi nhìn lại",
        "",
        "Hành trình không phải lúc nào cũng bằng phẳng. Có những ngày buồn đến phát khóc, có những lúc mệt mỏi, cô đơn đến mức muốn bỏ cuộc.",
        "",
        "Nhưng nếu được chọn lại một lần nữa, mình vẫn sẽ chọn Nhật, vẫn sẽ chọn ra đi, vẫn sẽ chọn hành trình này.",
      ],
      ja: [
        "日本留学の旅",
        "",
        "もうずいぶん久しぶりに、ノートパソコンを開いて、自分の日本留学の旅について数行書きました。すべてがあまりにも早く起こったため、時には最初の数日間の感情を忘れてしまいます。困惑と興奮が混ざり合い、少し震えを伴う感情です。今日、この物語を記録したいと思います。記憶を保つため、そして、いくつかの選択が私の人生全体を変えたことを自分に思い出させるためです。",
        "",
        "留学する決断—とてもシンプルな願望から始まりました",
        "",
        "あの頃、私は大きな夢を持っていませんでした。ただ、両親の腕から離れ、あまりにも慣れ親しんだすべてから離れて、自分自身に挑戦するために、遠く離れた場所で生活してみたかっただけです。",
        "",
        "当時、日本は私にとってまだ遠い存在で、兄姉の話、写真、そして勤勉で粘り強い人々の物語を通じてしか知らない国でした。",
        "",
        "そして準備が始まりました：書類、手続き、資金証明、面接…すべてが非常に順調に進み、おそらく私の考えよりも速く進みました。",
        "",
        "ただ一つだけ…出発前に日本語を学ぶ時間はわずか2ヶ月しかありませんでした。そんな長い旅路には、わずか2ヶ月という短い時間でした。",
        "",
        "出発の日—多くの感情が入り混じり、言葉では表現できません",
        "",
        "スーツケースを持って空港に行った日、その感覚を今でもはっきりと覚えています。すべてが混ざり合いました：胸の高鳴り、不安、期待、そして少しの恐怖も、到着したら兄姉と一緒に住むことを知っていたにもかかわらず。",
        "",
        "両親が手を振って別れを告げる瞬間、自然と自分が少し「大人になった」と感じましたが、同時に自分が異常に小さく感じました。",
        "",
        "長いフライトでしたが、不思議なことに、本当にあっという間に過ぎ去りました。",
        "",
        "日本での最初の数日—美しく、見慣れず、ホームシックに満ちていました",
        "",
        "初めて目にした日本は、とても清潔な空気、急いで歩く人々の流れ、時間通りすぎて…信じられない電車でした。",
        "",
        "しかし、まだ本当に追いついていないことを感じさせるものもありました：",
        "",
        "* 何度か道に迷ったこと",
        "",
        "* 日本語がまるで学んだことがないように聞こえたこと",
        "",
        "* そして毎晩、家と両親を思い出したこと",
        "",
        "それでも、日が経つにつれて、すべてに少しずつ慣れていきました。",
        "",
        "最初の日本語の文章を口ごもり始めました。指示なしで電車に乗る方法を自分で知るようになりました。最初の友人ができ始めました。",
        "",
        "そして、いつの間にか日本は静かに私の生活の一部となっていました。",
        "",
        "振り返ってみると",
        "",
        "旅路は常に平坦ではありませんでした。泣きたくなるほど悲しい日もあり、疲れ果て、孤独で諦めそうになる瞬間もありました。",
        "",
        "しかし、もう一度選べるとしたら、私はまだ日本を選ぶでしょう。まだ出発を選ぶでしょう。まだこの旅路を選ぶでしょう。",
      ],
    },
  },
  {
    slug: "why-did-i-even-study-abroad",
    title: "The Moment That Changed My Life",
    subtitle: "Why Did I Even Study Abroad?",
    category: "Life in Japan",
    date: "November 2025",
    // Multi-language support
    titleByLanguage: {
      en: "The Moment That Changed My Life",
      vi: "Khoảnh Khắc Thay Đổi Cuộc Đời Mình",
      ja: "人生を変えた瞬間",
    },
    subtitleByLanguage: {
      en: "Why Did I Even Study Abroad?",
      vi: "Du Học Để Làm Gì?",
      ja: "なぜ留学したのか？",
    },
    categoryByLanguage: {
      en: "Life in Japan",
      vi: "Cuộc Sống Ở Nhật",
      ja: "日本での生活",
    },
    content: [
      "On a rainy autumn evening in Japan, as the downpour blurred the world outside my small room, I lay on my bed staring out the window, letting my thoughts drift. Then suddenly, a question popped into my mind:",
      "\"Why did I study abroad?\"",
      "A question I wasn't asking anyone else—but asking myself.",
      "Wikipedia defines studying abroad as \"learning in another country to gain more knowledge, skills, or professional qualification, either by personal desire or by the requirement of a sponsoring organization.\" That's not wrong. But for me, it's only a very small part of the story.",
      "1. A life that felt rushed and mechanical",
      "Over the past months, I realized my days had been looping endlessly, like a cycle I didn't know how to escape. Every day was the same:",
      "– Go to school",
      "– Rush to my part-time job",
      "– And on the rare days I had off, I stayed at home: cleaning, grocery shopping, cooking…",
      "I hardly ever stepped outside just to live. I rarely gave myself the chance to experience anything new. I forgot that I once wanted to explore. I forgot how badly I wanted to experience. I forgot that it was this desire to live differently that brought me to Japan in the first place.",
      "2. The moment the question \"WHY DID I STUDY ABROAD?\" appeared in my mind",
      "And the moment that question echoed inside my head, it felt as if someone had pulled me out of the exhaustion I'd been drowning in.",
      "I looked at myself—someone who used to be so excited to explore Japan, to discover new streets, new places, new feelings—yet somehow had become trapped in the very life I created.",
      "I had been too busy to live. Too hurried to feel.",
      "That night, I sat up, opened my window, and let the cold breeze rush in. I didn't know whether it was the rain outside or something within me, but I felt something shift—small, subtle, but enough to make me want to live differently.",
      "I realized… maybe I needed to step out of this room. Step out of my fears, my laziness, my hesitation, and the invisible walls I built around myself.",
      "3. Starting again from the smallest things",
      "And from that night on, I began again—slowly, gently—from the smallest things.",
      "One evening after class, I wandered around by myself with no destination, no plan. I just wanted to give myself a moment to slow down, to breathe amid all the chaos and pressure.",
      "And after that day, sometimes I would randomly hop on a train to nowhere in particular, or simply sit somewhere watching people pass by.",
      "Those quiet, ordinary moments somehow softened my heart—as if they warmed something inside me that I had forgotten about.",
      "And then I understood… Studying abroad—for me—is also a journey of learning to listen to myself, learning to slow down, learning to uncover the feelings I buried under the rush of everyday life.",
      "Those purposeless train rides, the afternoons spent quietly watching strangers pass, or a simple aimless walk—those tiny moments reminded me that life still holds so many things worth experiencing.",
      "That I didn't come to Japan just to \"exist.\" I came here to live—to live the life I once dreamed of. To live a life that, when I look back someday, I can smile and say:",
      "\"Yes, I didn't waste my youth.\"",
    ],
    contentByLanguage: {
      en: [
        "The moment that changed my life: \"WHY DID I STUDY ABROAD?\"",
        "",
        "On a rainy autumn evening in Japan, as the downpour continued, from my small room, I lay on my bed, looking out the window and thinking about various things. Then, a question suddenly appeared in my mind: \"Why did I study abroad?\". A question that I myself asked to question myself.",
        "",
        "On Wikipedia, they define: \"Studying abroad is learning in another country to supplement knowledge, skills, and profession to satisfy one's learning needs or according to the requirements of a sponsoring organization.\" That's not wrong. But for me, that's only a very small part.",
        "",
        "1. A rushed, busy life",
        "",
        "Throughout the recent period, I realized my life kept spinning in circles like an endless loop. I kept struggling, not knowing how to break free. Every day was the same:",
        "– Go to school",
        "– Then rush to my part-time job",
        "– When I had days off, I also just stayed at home: cleaning, going to the supermarket to buy things, then cooking…",
        "",
        "I rarely stepped outside, rarely gave myself the opportunity to live differently.",
        "",
        "I forgot that I once wanted to experience.",
        "I forgot that I once wanted to explore.",
        "I forgot that it was the desire to live a different life that brought me to Japan.",
        "",
        "2. The moment the question \"WHY DID I STUDY ABROAD?\" appeared in my mind",
        "",
        "And right at the moment that question echoed in my head, I suddenly realized as if someone had just pulled me out of the exhausting cycle I had been stuck in for so long.",
        "",
        "I looked back at myself — someone who used to be excited to explore Japan, to experience every street corner, every new thing — yet now was trapped in my own life.",
        "",
        "It turned out, I had been too busy to live.",
        "Too rushed to feel.",
        "",
        "That night, I sat up, opened the window, let a bit of cold wind blow in. I didn't know if it was because of the rain outside or because of myself, but I felt something changing. Something very small, but enough to make me want to live differently.",
        "",
        "I realized… perhaps I need to step out of this room.",
        "Step out of my fears, my laziness, my procrastination, and even the limits I myself built.",
        "",
        "3. Starting again from the smallest things",
        "",
        "And from that day, I started again from the smallest things.",
        "",
        "That afternoon after school, I wandered alone, with no destination, no plan. I just wanted to give myself a period of time to slow down, to breathe the air amid the days full of busyness and pressure.",
        "",
        "So after that day, sometimes I also tried stepping onto a train with no destination, or sitting somewhere watching people pass by.",
        "",
        "Those seemingly ordinary moments made my heart soften, as if warmed by the simple things I had once unintentionally forgotten.",
        "",
        "And then I understood that…",
        "Studying abroad — for me — is also a journey of learning to listen to myself, learning to slow down, learning to find back the emotions that seemed to have been buried in the rush of life.",
        "",
        "Those purposeless train rides, those afternoons sitting quietly watching people pass by, or simply a purposeless walk… all those small things reminded me that this life still has so many things worth experiencing.",
        "That I didn't come to Japan just to \"exist\".",
        "I came here to live — to live a life I dreamed of.",
        "And to live a life that when I look back later, I can smile and say: \"Ah, I didn't miss my own youth.\"",
      ],
      vi: [
        "Khoảnh khắc thay đổi cuộc đời mình: \"DU HỌC ĐỂ LÀM GÌ?\"",
        "",
        "Vào một buổi tối chiều thu Nhật Bản, trời đổ mưa tầm tã, từ căn phòng nhỏ, mình nằm trên giường, nhìn ra ngoài cửa sổ và nghĩ ngợi linh tinh. Thế rồi, một câu hỏi bỗng xuất hiện trong đầu mình: \"Đi du học để làm gì?\". Một câu hỏi mà chính mình đặt ra để chất vấn bản thân.",
        "",
        "Trên Wikipedia, người ta định nghĩa: \"Du học là việc học tập ở một quốc gia khác để bổ sung kiến thức, kỹ năng, ngành nghề nhằm thỏa mãn nhu cầu học tập của bản thân hoặc theo yêu cầu của cơ quan, tổ chức tài trợ.\" Điều đó không sai. Nhưng với mình, đó chỉ là một phần rất nhỏ.",
        "",
        "1. Cuộc sống hối hả, bận rộn",
        "",
        "Suốt quãng thời gian vừa qua, mình nhận ra cuộc sống của mình cứ xoay vòng như một vòng lặp vô tận. Mình cứ loay hoay mãi, chẳng biết làm sao để thoát ra. Ngày nào cũng vậy:",
        "– Đi học",
        "– Rồi vội vã đi làm thêm",
        "– Đến khi có ngày nghỉ, mình cũng chỉ quanh quẩn ở nhà: dọn dẹp, đi siêu thị mua đồ, rồi nấu ăn…",
        "",
        "Hiếm khi mình bước chân ra ngoài, hiếm khi cho bản thân cơ hội sống khác đi.",
        "",
        "Mình quên mất rằng mình từng muốn trải nghiệm.",
        "Mình quên mất rằng mình từng muốn khám phá.",
        "Mình quên mất rằng chính mong muốn được sống một cuộc đời khác đi đã đưa mình đến Nhật Bản.",
        "",
        "2. Khoảnh khắc câu hỏi \"DU HỌC ĐỂ LÀM GÌ?\" xuất hiện trong đầu mình",
        "",
        "Và ngay khoảnh khắc câu hỏi ấy vang lên trong đầu, mình chợt nhận ra như có ai đó vừa kéo mình ra khỏi guồng quay mệt mỏi bấy lâu nay.",
        "",
        "Mình nhìn lại bản thân — một đứa từng háo hức muốn khám phá Nhật Bản, muốn trải nghiệm từng góc phố, từng điều mới mẻ — vậy mà giờ đây lại bị mắc kẹt trong chính cuộc sống của mình.",
        "",
        "Hóa ra, mình đã quá bận để sống.",
        "Quá vội để cảm nhận.",
        "",
        "Đêm hôm đó, mình ngồi dậy, mở cửa sổ, để một chút gió lạnh lùa vào. Không biết vì mưa ngoài kia hay vì chính mình, nhưng mình cảm thấy có gì đó đang thay đổi. Một điều gì đó rất nhỏ, nhưng đủ để mình muốn sống khác đi.",
        "",
        "Mình nhận ra… có lẽ mình cần bước ra khỏi căn phòng này.",
        "Bước ra khỏi nỗi sợ, sự lười, sự trì hoãn, và cả những giới hạn mà chính mình dựng lên.",
        "",
        "3. Bắt đầu lại từ những điều nhỏ nhất",
        "",
        "Và từ hôm đó, mình bắt đầu lại từ những điều nhỏ nhất.",
        "",
        "Chiều tan học hôm ấy, mình lang thang một mình, chẳng có điểm đến, cũng chẳng có kế hoạch. Mình chỉ muốn để bản thân có một khoảng thời gian được sống chậm lại, được hít thở bầu không khí giữa những ngày tháng đầy bộn bề và áp lực.",
        "",
        "Vậy là sau hôm ấy, thỉnh thoảng mình cũng thử bước lên một chuyến tàu vô định, hoặc ngồi một chỗ nhìn dòng người qua lại.",
        "",
        "Những khoảnh khắc tưởng chừng bình thường ấy lại làm trái tim mình dịu lại, như được sưởi ấm bởi chính những điều giản đơn mà mình từng vô tình bỏ quên.",
        "",
        "Và rồi mình hiểu rằng…",
        "Du học — với mình — còn là hành trình học cách lắng nghe chính mình, học cách sống chậm lại, học cách tìm lại những cảm xúc tưởng như đã bị vùi lấp trong guồng quay hối hả của cuộc sống.",
        "",
        "Những chuyến tàu vô định, những chiều ngồi lặng nhìn dòng người qua lại, hay chỉ đơn giản là một buổi đi dạo không mục đích… tất cả những điều nhỏ bé ấy đã nhắc mình nhớ rằng cuộc sống này vẫn còn rất nhiều điều đáng để trải nghiệm.",
        "Rằng mình không đến Nhật chỉ để \"tồn tại\".",
        "Mình đến đây để sống — sống một cuộc đời mà mình mơ ước.",
        "Và để sống một cuộc đời mà sau này nhìn lại, mình có thể mỉm cười và nói rằng: \"À, mình đã không bỏ lỡ thanh xuân của chính mình.\"",
      ],
      ja: [
        "人生を変えた瞬間：「留学するのは何のため？」",
        "",
        "日本の雨の秋の夜、激しい雨が降り続く中、小さな部屋から、ベッドに横たわり、窓の外を見つめながら、あれこれ考えていました。そして突然、頭に質問が浮かびました：「留学するのは何のため？」。自分自身に問いかける質問です。",
        "",
        "Wikipediaでは、次のように定義されています：「留学とは、個人の願望またはスポンサー組織の要件により、より多くの知識、スキル、職業資格を得るために別の国で学習することです。」それは間違っていません。しかし、私にとって、それは物語のごく一部に過ぎません。",
        "",
        "1. 慌ただしく、忙しい生活",
        "",
        "最近の期間、私の生活が無限ループのように回転していることに気づきました。どうやって抜け出すかわからず、ずっともがき続けていました。毎日同じでした：",
        "– 学校に行く",
        "– そして急いでアルバイトに行く",
        "– 休みの日になると、家にいて：掃除、スーパーで買い物、そして料理…",
        "",
        "ほとんど外に出ることはなく、自分に異なる生活をする機会を与えることはほとんどありませんでした。",
        "",
        "かつて体験したいと思っていたことを忘れていました。",
        "かつて探求したいと思っていたことを忘れていました。",
        "異なる生活をしたいという願望が、最初に私を日本に連れてきたことを忘れていました。",
        "",
        "2. 「留学するのは何のため？」という質問が頭に浮かんだ瞬間",
        "",
        "そして、その質問が頭の中で響いた瞬間、誰かが私を長い間溺れさせていた疲労から引き出してくれたような気がしました。",
        "",
        "私は自分自身を見ました。かつて日本を探求し、各街角、各新しいことを体験することに興奮していた人。しかし、今では自分の作った生活に閉じ込められていました。",
        "",
        "結局、私は生きるのに忙しすぎました。",
        "感じるのに急ぎすぎました。",
        "",
        "その夜、私は起き上がり、窓を開け、少し冷たい風を入れました。外の雨なのか、自分自身なのかわかりませんが、何かが変化しているのを感じました。とても小さなことですが、異なる生き方をしたいと思わせるには十分でした。",
        "",
        "私は気づきました…おそらく、この部屋から出る必要があるのかもしれません。",
        "恐怖、怠惰、ためらい、そして自分自身が築いた限界から出る必要があります。",
        "",
        "3. 最小のものから再び始める",
        "",
        "そして、あの日から、私は最小のものから再び始めました。",
        "",
        "あの日の放課後、私は一人でぶらつき、目的地も計画もありませんでした。ただ、自分に少し時間をかけて、忙しさと圧力に満ちた日々の中で息をする機会を与えたかっただけです。",
        "",
        "そうして、あの日以来、時々、無目的に電車に乗ったり、どこかに座って人々が通り過ぎるのを見たりすることもありました。",
        "",
        "一見普通に見えるこれらの瞬間が、私の心を和らげ、かつて無意識に忘れていたシンプルなものによって温められたように感じました。",
        "",
        "そして、私は理解しました…",
        "留学—私にとって—は、自分自身に耳を傾けることを学び、生活のペースを遅らせることを学び、生活の慌ただしさの中で埋もれてしまった感情を見つけ直すことを学ぶ旅でもあります。",
        "",
        "無目的な電車の旅、静かに人々が通り過ぎるのを見つめる午後、または単純な無目的な散歩…これらの小さなことが、人生にはまだ体験する価値のある多くのことがあることを思い出させてくれました。",
        "私は日本に「存在する」ためだけに来たのではありません。",
        "私はここに来て、かつて夢見た人生を生きるためです。",
        "そして、後で振り返ったとき、笑顔で言えるような人生を生きるためです：「ああ、私は自分の青春を無駄にしなかった。」",
      ],
    },
  },
  {
    slug: "the-art-of-cooking",
    title: "When Cooking Became Part of My Life",
    subtitle: "A Recipe for Life",
    category: "Cooking",
    date: "November 2025",
    content: [],
    // Multi-language support
    titleByLanguage: {
      en: "When Cooking Became Part of My Life",
      vi: "Khi Nấu Ăn Trở Thành Một Phần Cuộc Sống Của Mình",
      ja: "料理が人生の一部になったとき",
    },
    subtitleByLanguage: {
      en: "The Simple Joy of Cooking",
      vi: "Niềm Vui Đơn Giản Từ Việc Nấu Ăn",
      ja: "料理のシンプルな喜び",
    },
    categoryByLanguage: {
      en: "Cooking",
      vi: "Nấu Ăn",
      ja: "料理",
    },
    dateByLanguage: {
      en: "November 2025",
      vi: "Tháng 11 2025",
      ja: "2025年11月",
    },
    contentByLanguage: {
      en: [
        "When Cooking Became Part of My Life",
        "",
        "The Simple Joy of Cooking",
        "",
        "Content coming soon...",
      ],
      vi: [
        "Khi Nấu Ăn Trở Thành Một Phần Cuộc Sống Của Mình",
        "",
        "Niềm Vui Đơn Giản Từ Việc Nấu Ăn",
        "",
        "Nội dung đang được cập nhật...",
      ],
      ja: [
        "料理が人生の一部になったとき",
        "",
        "料理のシンプルな喜び",
        "",
        "コンテンツはまもなく公開されます...",
      ],
    },
  },
  {
    slug: "exploring-the-world",
    title: "Exploring the World",
    subtitle: "Unforgettable Journeys",
    category: "Explore & Travel",
    date: "November 2025",
    content: [],
    // Multi-language support
    titleByLanguage: {
      en: "Exploring the World",
      vi: "Khám Phá Thế Giới",
      ja: "世界を探索する",
    },
    subtitleByLanguage: {
      en: "Unforgettable Journeys",
      vi: "Những Chuyến Đi Đáng Nhớ",
      ja: "忘れられない旅",
    },
    categoryByLanguage: {
      en: "Explore & Travel",
      vi: "Khám Phá & Du Lịch",
      ja: "探索と旅行",
    },
    dateByLanguage: {
      en: "November 2025",
      vi: "Tháng 11 2025",
      ja: "2025年11月",
    },
    contentByLanguage: {
      en: [
        "Exploring the World",
        "",
        "Unforgettable Journeys",
        "",
        "Content coming soon...",
      ],
      vi: [
        "Khám Phá Thế Giới",
        "",
        "Những Chuyến Đi Đáng Nhớ",
        "",
        "Nội dung đang được cập nhật...",
      ],
      ja: [
        "世界を探索する",
        "",
        "忘れられない旅",
        "",
        "コンテンツはまもなく公開されます...",
      ],
    },
  },
];

export {
  services,
  technologies,
  experiences,
  testimonials,
  projects,
  programs,
};
